### PR TITLE
GraphSON

### PR DESCRIPTION
**Pull request by Blondysinger**
New Interface IGraphSONIterable

The change allows GraphSONUtility to use any kind of type that implements IGraphSONIterable. In this way not only List, Map, Array or Element, but all the wrapper that implements IGraphSONIterable, such as OrientElementIterable, will return a valid value from the jsonFromElement method.

### CODE REVIEW

**Comment by spmallette** [comment]
I can't quite remember why this was implemented this way. Unless you can think of a good reason, I think that it might be better that `GraphSONUtility` simply support `Iterable` and `Iterator` - as opposed to adding a new interface.  Of course, note that we are very close to releasing TP3 and that it isn't terribly likely that we will release a 2.7.0 of Blueprints.  In TP3, I'm pretty sure that we treat all matters related to serialization as an `Iterator` so I would think that would work well with `OrientElementIterable` without any change.

**Comment by Blondysinger** [comment]
I don't know when the realease of TP3 is due and when the graph dbs will be compliant with it, so I had to use the 2.6 version with regard to the use case below:

In the use of the jsonFromElement method we can specify a Set of propreties that belong to a vertex of the graph, but the inside method createJSONMap compares the propertyKeys to List, Map and Array. Otherwise the method writes the toString of the value (OrientElementIterable).

Thus:

{"in_friend":"com.tinkerpop.blueprints.impls.orient.OrientElementIterable@23484688","_id":"#13:11","_type":"vertex”}


All the methods of GraphSONUtility are private, so it isn't possible to create an extension.
I've simply resolved this by a "copy and paste" of the GraphSONUtility class in my project, but I've thought that this more generic solution would be useful for the community:

I've created the IGraphSONIterable with the method

public List<? extends Element> getList()


I've modified OrientElementIterable to make it implement that interface:

	@Override
	public List<? extends Element> getList() {
		List<T> result = new ArrayList<T>();
		for (Iterator<T> iterator = iterator(); iterator.hasNext();) {
			T e = (T) iterator.next();
			result.add(e);
		}
		return result;
	}

Therefore, the expected final result is for example:

{"in_friend":[{"_id":"#12:12","_type":"edge","_outV":"#13:22","_inV":"#13:11","_label":"friend"},{"_id":"#12:14","_type":"edge","_outV":"#13:23","_inV":"#13:11","_label":"friend"},{"_id":"#12:16","_type":"edge","_outV":"#13:24","_inV":"#13:11","_label":"friend"},{"_id":"#12:18","_type":"edge","_outV":"#13:25","_inV":"#13:11","_label":"friend"},{"_id":"#12:20","_type":"edge","_outV":"#13:26","_inV":"#13:11","_label":"friend"},{"_id":"#12:22","_type":"edge","_outV":"#13:27","_inV":"#13:11","_label":"friend"}],"_id":"#13:11","_type":"vertex"}

**Comment by spmallette** [comment]
I understand why you did this, but what I don't understand is why you need to create a new interface to do it.  Is there any reason why you wouldn't just modify `GraphSONUtility` to deal with `Iterable` and `Iterator` which is an even more generalized approach.  Just check the type of `value` for those two things and convert them to `List`.  Why would it be better to introduce a new interface when this will work for `OrientElementIterable` without any change to it?  Am I missing something in your approach?

**Comment by Blondysinger** [comment]
Yes, you are right. I have modified the PR

**Comment by spmallette** [comment]
Merged - with some added tests and support for `Iterator`.  Thanks.

**Pull request merged**
