### PR TITLE
Improved osgi packaging and manifest headers.

### PR DESCRIPTION
**Pull request by splatch**
By default tinkerpop does not provide OSGi metadata which is just few extra manifest entries. I am open to backport this fix to 2.6.0 if mainanance release is planned.

### CODE REVIEW

**Comment by spmallette** [comment]
Thanks for the pull request, but unfortunately we must decline its acceptance.  At this point, I don't think that we will be doing another release of TinkerPop 2.x given the release timeline of TinkerPop3:

https://groups.google.com/d/msg/gremlin-users/tYHoyIAQCeo/BOHqO_HtzJAJ

TinkerPop3 is not OSGi compliant - perhaps it will be something for future consideration.

**Comment by splatch** [comment]
If so, will provide patch for 3.x before it gets GA. :-) Thx for feedback.

**Comment by spmallette** [comment]
We really aren't interested in supporting OSGi and the overhead that it might bring to our project. As such your PR will not likely be accepted there either at this time.  We've had a number of discussions on this for years - many of which you can dig into in the mailing list and in GitHub issues on various TinkerPop projects.  We are currently tracking OSGi discussion in Titan's issue tracker on this:

https://github.com/thinkaurelius/titan/issues/780

where it is under consideration.  Please feel free to add your thoughts there.

**Comment by splatch** [comment]
Don't be so close for new improvements. Since you are now in apache incubation process please be open for community suggestions which might lead to expanded project usage and easier adoption of it. Couple of additional manifest entries doesn't cost you anything at all and you can shift mainanance of these to somebody else (for example me).
I have made some work around fasterxml osgification in mid of 2013 (https://github.com/FasterXML/oss-parent/pull/5) and since then there was only one or two issues with *updating* maven bundle plugin itself, or malformed osgi manifest entry, but not with produced artifacts itself. Doesn't look bad for project used so widely, isn't?
Belive me - nobody wants to complicate things. I am focused on osgification of tinkerpop blueprints at this moment and I don't really want to touch titan with all its dependencies yet.

Anyway - I consider this issue as closed, will continue going with it over ASF.

**Comment by spmallette** [comment]
Thanks for your thoughts and your offer to contribute.  For clarity, I wasn't suggesting that you involve yourself in Titan - I just meant that I am tracking that OSGi discussion over there as an open issue as it pertains to TinkerPop.  

Now, regarding external contributions, we are not closed to new improvements or community suggestions just because we did not accept this pull request or because OSGi is not something we have chosen to support right now.  Please don't mistake cautious consideration of pull requests for being "closed".  

This OSGi issue is raised once or twice a year in TinkerPop by individuals who consider OSGi an improvement, yet no TinkerPop member (core contributors or vendor contributors) or other long-standing member of the TinkerPop community (i.e. someone who has contributed other PRs over the years, is active on the mailing lists, etc.) is willing to stand up for it as such.  This is even true for those with some OSGi experience.  Lacking a community recognized "champion" makes it harder for us to adopt it and make it part of what we commit to maintaining.

**Pull request closed without merging**
